import { QueryProvider } from "@/components/query-provider"
import { ThemeProvider } from "@/components/theme-provider"
import { DotPattern } from "@/components/ui/dot-pattern"
import { Toaster } from "@/components/ui/sonner"
import { TooltipProvider } from "@/components/ui/tooltip"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Josefin_Sans } from "next/font/google"
import "./globals.css"

const josefinSans = Josefin_Sans({
	subsets: ["latin"],
	variable: "--font-sans",
})

export const metadata: Metadata = {
	title: "Oraha Finances",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<>
			<html
				lang="ptBR"
				suppressHydrationWarning
				className={cn("font-sans", josefinSans.variable)}
			>
				<head />
				<body className="relative">
					<QueryProvider>
						<ThemeProvider
							attribute="class"
							defaultTheme="system"
						>
							<DotPattern className="fixed -z-10 text-foreground/15" />
							<TooltipProvider>{children}</TooltipProvider>
							<Toaster />
						</ThemeProvider>
					</QueryProvider>
				</body>
			</html>
		</>
	)
}
