import { QueryProvider } from '@/components/query-provider'
import { ThemeProvider } from '@/components/theme-provider'
import { DotPattern } from '@/components/ui/dot-pattern'
import { Toaster } from '@/components/ui/sonner'
import type { Metadata } from 'next'
import { Josefin_Sans, Geist } from 'next/font/google'
import './globals.css'
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const josefinSans = Josefin_Sans({
  variable: '--font-josefin-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <html
        lang="ptBR"
        suppressHydrationWarning className={cn("font-sans", geist.variable)}
      >
        <head />
        <body className={`${josefinSans.className} relative`}>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
            >
              <DotPattern className="fixed -z-10 text-foreground/15" />
              {children}
              <Toaster />
            </ThemeProvider>
          </QueryProvider>
        </body>
      </html>
    </>
  )
}
